// 输出格式：主题 CSS（--klc-*）、TS Theme 源文件、自包含的 DTCG 解析器包。
import { cssVarName } from './css-value.mjs'
import { isToken, walkTokens } from './resolver.mjs'

/** themeToCssVars 的族顺序：colors → spacing → typography → motion。 */
export const THEME_GROUP_ORDER = ['color', 'spacing', 'typography', 'motion']

const GENERATED = (src) =>
  `// 生成文件：由 \`pnpm tokens:build\` 从 src/foundation/tokens/dtcg/${src} 生成，请勿手改。`

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

/**
 * 主题层 CSS：与 `toCssDeclarationBlock(themeToCssVars(theme))` 逐字节一致。
 * `isThemePath` 判定 token 是否属于 Theme 契约（colors/spacing/typography/motion）。
 */
export function emitThemeCss(input, sdTree, isThemePath) {
  const decls = []
  for (const group of THEME_GROUP_ORDER) {
    if (!sdTree[group]) continue
    for (const [path, token] of walkTokens(sdTree[group], [group])) {
      if (!isThemePath(path)) continue
      decls.push(`  ${cssVarName(path)}: ${String(token.$value)};`)
    }
  }
  return [
    `/* Generated by \`pnpm tokens:build\`: preset=${input.preset}, mode=${input.mode}. Do not edit. */`,
    `:root {\n${decls.join('\n')}\n}`,
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function lit(v) {
  if (typeof v === 'number') return String(v)
  return v.includes("'") ? JSON.stringify(v) : `'${v}'`
}

function comment(desc, indent) {
  if (!desc) return []
  return desc.split('\n').map((l) => `${indent}//${l ? ` ${l}` : ''}`)
}

function jsdoc(desc) {
  if (!desc) return []
  return ['/**', ...desc.split('\n').map((l) => (l ? ` * ${l}` : ' *')), ' */']
}

const aliasOf = (token) => {
  const m = typeof token.$value === 'string' && token.$value.match(/^\{([^}]+)\}$/)
  return m ? m[1] : null
}

/**
 * 输出对象字面量。`refs` 把别名前缀映射为 TS 标识符（如 `dark.interface` →
 * `darkInterfaceColors`），从而还原手写源码里的引用关系，而不是展开成字面量。
 */
function objectLiteral(raw, sd, indent, refs = {}) {
  const lines = []
  const keys = Object.keys(raw).filter((k) => !k.startsWith('$'))
  for (const key of keys) {
    const node = raw[key]
    if (isToken(node)) {
      const alias = aliasOf(node)
      const ref = alias && Object.entries(refs).find(([p]) => alias.startsWith(`${p}.`))
      const line = ref
        ? `${indent}${key}: ${ref[1]}.${alias.slice(ref[0].length + 1)},`
        : `${indent}${key}: ${lit(sd[key].$value)},`
      // 单行短说明作为行尾注释，其余放在键之前（与手写源码一致）。
      const desc = node.$description
      const trailing = desc && !desc.includes('\n') && `${line} // ${desc}`
      if (trailing && trailing.length <= 100) lines.push(trailing)
      else lines.push(...comment(desc, indent), line)
      continue
    }
    lines.push(...comment(node.$description, indent))
    // 整组 1:1 引用同一来源组时输出标识符本身（如 `ui: darkInterfaceColors`）。
    const childKeys = Object.keys(node).filter((k) => !k.startsWith('$'))
    const whole = Object.entries(refs).find(([p]) =>
      childKeys.every((k) => isToken(node[k]) && aliasOf(node[k]) === `${p}.${k}`),
    )
    if (whole) {
      lines.push(`${indent}${key}: ${whole[1]},`)
      continue
    }
    lines.push(`${indent}${key}: {`)
    lines.push(...objectLiteral(node, sd[key], `${indent}  `, refs))
    lines.push(`${indent}},`)
  }
  return lines
}

export function emitThemeTs(mode, raw, sdTree) {
  const ident = `${mode}InterfaceColors`
  const color = raw[mode].color
  return [
    GENERATED(`scheme/${mode}.tokens.json`),
    ...jsdoc(color.$description),
    '',
    `import { ${ident} } from './interface-colors.js'`,
    "import { motion, spacing, typography } from './theme-base.js'",
    "import type { Theme } from './types.js'",
    '',
    `export const ${mode}Theme: Theme = {`,
    `  name: '${mode}',`,
    '  spacing,',
    '  typography,',
    '  motion,',
    '  colors: {',
    ...objectLiteral(color, sdTree[mode].color, '    ', { [`${mode}.interface`]: ident }),
    '  },',
    '}',
    '',
  ].join('\n')
}

export function emitInterfaceColorsTs(raw, sdTree) {
  const out = [GENERATED('scheme/{dark,light}.tokens.json')]
  const desc = raw.dark.interface.$description
  out.push(...comment(desc, ''), "import type { UiColors } from './types.js'", '')
  for (const mode of ['dark', 'light']) {
    out.push(`export const ${mode}InterfaceColors: UiColors = {`)
    out.push(...objectLiteral(raw[mode].interface, sdTree[mode].interface, '  '))
    out.push('}', '')
  }
  return out.join('\n')
}

export function emitThemeBaseTs(raw, sdTree, themeBaseDoc) {
  const types = { spacing: 'SpacingTokens', typography: 'TypographyTokens', motion: 'MotionTokens' }
  const out = [
    GENERATED('foundation/theme-base.tokens.json'),
    "import type { MotionTokens, SpacingTokens, TypographyTokens } from './types.js'",
    '',
  ]
  for (const group of ['spacing', 'typography', 'motion']) {
    // 只输出 Theme 契约内的键（v2 新增的同组 token 不进入 legacy 家族）。
    const legacy = Object.fromEntries(
      Object.entries(raw[group]).filter(([k]) => k in themeBaseDoc[group]),
    )
    out.push(`export const ${group}: ${types[group]} = {`)
    out.push(...objectLiteral(legacy, sdTree[group], '  '))
    out.push('}', '')
  }
  return out.join('\n')
}

export function emitVisualPalettesTs(presets) {
  const out = [
    GENERATED('preset/*.tokens.json'),
    '// 视觉风格的语义色表；市场涨跌沿用 base，不将强调色用作行情颜色。',
    "import type { VisualPalette } from '../types.js'",
    '',
  ]
  for (const { id, description, raw, sdTree } of presets) {
    out.push(...comment(description, ''))
    out.push(`export const ${id} = {`)
    for (const mode of ['dark', 'light']) {
      out.push(`  ${mode}: {`)
      out.push(...objectLiteral(raw[mode].visual, sdTree[mode].visual, '    '))
      out.push('  },')
    }
    out.push("} satisfies Record<'light' | 'dark', VisualPalette>", '')
  }
  return out.join('\n')
}

// ---------------------------------------------------------------------------
// DTCG bundle
// ---------------------------------------------------------------------------

/** 把 resolver 中的文件 `$ref` 内联为源对象，得到单文件、可移植的 DTCG 解析器文档。 */
export function bundleResolver(doc, load) {
  const inlineSources = (sources) =>
    sources.map((s) => (s.$ref?.startsWith('#/') ? s : load(s.$ref)))
  const out = structuredClone(doc)
  out.description = `${doc.description} Bundled: file sources inlined by \`pnpm tokens:build\`.`
  for (const set of Object.values(out.sets ?? {})) set.sources = inlineSources(set.sources)
  for (const mod of Object.values(out.modifiers ?? {}))
    for (const [ctx, sources] of Object.entries(mod.contexts))
      mod.contexts[ctx] = inlineSources(sources)
  return out
}
