// DTCG Resolver Module 2025.10 的最小实现：按 resolutionOrder 合并 sets 与选中的
// modifier context，别名留待合并完成后由 Style Dictionary 统一解析（规范要求）。
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const CORE_DIR = fileURLToPath(new URL('../../../', import.meta.url))
export const TOKENS_DIR = path.join(CORE_DIR, 'src/foundation/tokens')
export const DTCG_DIR = path.join(TOKENS_DIR, 'dtcg')
export const RESOLVER_FILE = 'kcq.resolver.json'

/** scheme 中不对外选择的私有分组：interface 为 Pro 原始界面色，visual 为预设色表。 */
export const PRIVATE_GROUPS = new Set(['interface', 'visual'])
export const MODES = ['light', 'dark']

export function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'))
}

export function isToken(node) {
  return node !== null && typeof node === 'object' && !Array.isArray(node) && '$value' in node
}

export function loadResolver(dir = DTCG_DIR) {
  const doc = readJson(path.join(dir, RESOLVER_FILE))
  if (doc.version !== '2025-10-01') throw new Error(`resolver version ${doc.version} unsupported`)
  return { dir, doc }
}

/** 全部 modifier 输入的笛卡尔积，按 modifier 与 context 的声明顺序。 */
export function permutations({ doc }) {
  let out = [{}]
  for (const [name, mod] of Object.entries(doc.modifiers ?? {})) {
    out = out.flatMap((p) => Object.keys(mod.contexts).map((ctx) => ({ ...p, [name]: ctx })))
  }
  return out
}

function loadSource(resolver, source, seen) {
  if (!('$ref' in source)) return [source]
  const ref = source.$ref
  if (ref.startsWith('#/sets/')) {
    const set = resolver.doc.sets[ref.slice('#/sets/'.length)]
    if (!set) throw new Error(`unknown set ${ref}`)
    return set.sources.flatMap((s) => loadSource(resolver, s, seen))
  }
  if (ref.startsWith('#/')) throw new Error(`unsupported pointer ${ref}`)
  seen?.add(ref)
  // overrides：构建过程中尚未落盘的生成源（mode 选择器），保证 --check 不读到旧文件。
  const pending = resolver.overrides?.get(ref)
  return [pending ? structuredClone(pending) : readJson(path.join(resolver.dir, ref))]
}

/** 叶子 token 整体替换，分组逐键合并；已有键保持原位，保证输出顺序稳定。 */
export function mergeTokens(base, layer) {
  const out = { ...base }
  for (const [key, value] of Object.entries(layer)) {
    const prev = out[key]
    if (
      isToken(value) ||
      value === null ||
      typeof value !== 'object' ||
      Array.isArray(value) ||
      prev === undefined ||
      isToken(prev) ||
      typeof prev !== 'object'
    )
      out[key] = structuredClone(value)
    else out[key] = mergeTokens(prev, value)
  }
  return out
}

/** 解析一个排列：返回合并后的原始 DTCG 树（别名未解析）。 */
export function resolveTokens(resolver, input, seen) {
  let tree = {}
  for (const entry of resolver.doc.resolutionOrder) {
    const ref = entry.$ref
    let sources
    if (ref.startsWith('#/sets/')) sources = [entry]
    else if (ref.startsWith('#/modifiers/')) {
      const name = ref.slice('#/modifiers/'.length)
      const mod = resolver.doc.modifiers[name]
      const ctx = input[name] ?? mod.default
      sources = mod.contexts[ctx]
      if (!sources) throw new Error(`modifier ${name}: unknown context ${ctx}`)
    } else throw new Error(`unsupported resolutionOrder entry ${ref}`)
    for (const s of sources)
      for (const src of loadSource(resolver, s, seen)) tree = mergeTokens(tree, src)
  }
  return tree
}

/** 深度优先遍历 token（保持声明顺序）。 */
export function* walkTokens(node, path = []) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue
    if (isToken(value)) yield [[...path, key], value]
    else if (value && typeof value === 'object') yield* walkTokens(value, [...path, key])
  }
}

export function getAt(node, path) {
  return path.reduce((n, k) => n?.[k], node)
}

/**
 * mode 选择器：把 scheme 中 `<mode>.*` 分支别名到公开名称（`color.*` 等）。
 * 由构建生成，保证每个 scheme token 都被选中、且不会悬空。
 */
export function buildModeSelector(mode, schemeDoc) {
  const branch = schemeDoc[mode]
  const out = {
    $description: `Generated by \`pnpm tokens:build\` from scheme/${mode}.tokens.json; do not edit. Mode context "${mode}": aliases the \`${mode}.*\` branch (after preset overrides) onto the public token names.`,
  }
  for (const [group, node] of Object.entries(branch)) {
    if (group.startsWith('$') || PRIVATE_GROUPS.has(group)) continue
    const copy = (n, p) => {
      const o = {}
      for (const [k, v] of Object.entries(n)) {
        if (k.startsWith('$')) continue
        o[k] = isToken(v)
          ? { $type: v.$type, $value: `{${[mode, ...p, k].join('.')}}` }
          : copy(v, [...p, k])
      }
      return o
    }
    out[group] = copy(node, [group])
  }
  return out
}
