export const AGENT_COMMAND_CHANNEL = 'kq-agent:command'
export const AGENT_CONNECT_CHANNEL = 'kq-agent:connect'
export const AGENT_IDENTITY_CHANNEL = 'kq-agent:identity'
export const AGENT_PORT_CHANNEL = 'kq-agent:port'
export const AGENT_CHART_ID = 'primary'
export const AGENT_PORT_UI_MESSAGE = 'agent.ui'
export const AGENT_PORT_TOOL_REQUEST = 'renderer.tool.request'
export const AGENT_PORT_TOOL_RESPONSE = 'renderer.tool.response'
