// Agent 界面文案数据与按语言取用的访问器。

import type { AgentLocale } from '../types.js'

const copy = {
  en: {
    agent: 'Agent Alpha',
    timeline: 'Agent timeline',
    newSession: 'New session',
    renameSession: 'Rename session',
    deleteSession: 'Delete session',
    sessions: 'Conversations',
    openSessions: 'Show conversations',
    closeSessions: 'Hide conversations',
    noSessions: 'No conversations yet',
    settings: 'Model settings',
    openPanel: 'Open Agent panel',
    closePanel: 'Close Agent panel',
    interface: 'Interface',
    language: 'Language',
    connected: 'Connected',
    testing: 'Testing',
    emptyTitle: 'Start a new exploration',
    emptyBody: 'AI-native chart, with the agent as a first-class citizen.',
    promptTrend: 'Summarize the current trend and key levels',
    promptRsi: 'Analyze RSI(14) over the latest 20 bars',
    promptEma: 'Add EMA(20) to the main chart',
    promptBond: 'Compare bond trends across different durations',
    readOnly: 'Read-only',
    readOnlyHint: 'Block chart changes',
    noSymbol: 'No symbol',
    injectedKLineBars: 'Injection preview',
    injectedKLineBarsCount: 'ContextItems injected',
    composerPlaceholder: 'Ask about this chart...',
    send: 'Send',
    stop: 'Stop',
    action: 'Action',
    reasoning: 'Reasoning',
    reasoningEffort: 'Reasoning effort',
    collapseReasoning: 'Collapse reasoning',
    input: 'Input',
    output: 'Output',
    total: 'Total',
    result: 'Result',
    evidence: 'Evidence',
    locate: 'Locate on chart',
    undo: 'Undo',
    retry: 'Retry',
    copyMessage: 'Copy',
    copiedMessage: 'Copied',
    copyFailed: 'Copy failed',
    regenerate: 'Regenerate',
    editMessage: 'Edit message',
    saveAndSend: 'Save and send',
    editFailed: 'Could not send the edited message.',
    editBusy: 'Wait for the current response to finish before editing.',
    editUnavailable: 'This message is no longer in the current conversation.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    reject: 'Reject',
    reversible: 'Reversible',
    irreversible: 'Not reversible',
    required: 'Confirmation required',
    recommended: 'Recommended action',
    question: {
      required: 'Clarification required',
      submit: 'Send answer',
      freeText: 'Or type your own requirement',
      answered: 'Answered',
      cancelled: 'Question cancelled',
    },
    tokens: 'tokens',
    providerSettings: 'Provider settings',
    tools: 'Tools',
    noTools: 'No Agent tools are registered.',
    toolParameters: 'Parameters (JSON)',
    toolRun: 'Run',
    toolRunning: 'Running...',
    providerProfile: 'Configuration',
    managedProviderNotice:
      'This configuration is provided and managed for you. No API key or model selection is needed.',
    providerProfileName: 'Configuration name',
    providerProfileNameDuplicated: 'A configuration with this name already exists.',
    newProviderProfile: 'New configuration',
    renameProviderProfile: 'Rename configuration',
    deleteProviderProfile: 'Delete configuration',
    deleteProviderProfileConfirm: 'Delete this configuration? Its model pool is removed too.',
    apiProtocol: 'API protocol',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: 'Leave blank to keep the saved key',
    save: 'Save',
    additionalHeaders: 'Additional headers (JSON)',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "My app"\n}',
    model: 'Select a model',
    modelList: 'Available models',
    modelPool: 'Model pool',
    contextWindow: 'Context',
    noModelsInPool: 'Add at least one model to the model pool.',
    loadingModels: 'Loading models...',
    refreshModels: 'Refresh model list',
    modelSearchPlaceholder: 'Search',
    apiKeyPlaceholder: 'Leave blank to use the saved credential',
    modelPlaceholder: 'Select a model',
    sessionNamePrompt: 'Session name',
    deleteSessionConfirm: 'Delete this session?',
    status: {
      idle: 'Ready',
      running: 'Running',
      cancelling: 'Stopping',
      completed: 'Completed',
      failed: 'Failed',
      cancelled: 'Cancelled',
      partial: 'Partially completed',
      interrupted: 'Interrupted',
      queued: 'Queued',
      'requires-confirmation': 'Waiting for confirmation',
      succeeded: 'Succeeded',
      confirmed: 'Confirmed',
      rejected: 'Rejected',
      expired: 'Expired',
      undone: 'Undone',
    },
  },
  'zh-CN': {
    agent: 'Agent Alpha',
    timeline: 'Agent 时间线',
    newSession: '新建会话',
    renameSession: '重命名会话',
    deleteSession: '删除会话',
    sessions: '对话列表',
    openSessions: '展开对话列表',
    closeSessions: '收起对话列表',
    noSessions: '暂无对话',
    settings: '模型设置',
    openPanel: '打开智能体面板',
    closePanel: '关闭 Agent 面板',
    interface: '界面',
    language: '语言',
    connected: '已连接',
    testing: '测试中',
    emptyTitle: '开始新的探索',
    emptyBody: 'AI 原生图表，智能体是一等公民',
    promptTrend: '总结当前趋势和关键价位',
    promptRsi: '分析最近 20 根 K 线的 RSI(14)',
    promptEma: '在主图添加 EMA(20)',
    promptBond: '比较不同久期的债券走势',
    readOnly: '只读',
    readOnlyHint: '禁止修改图表',
    noSymbol: '无标的',
    injectedKLineBars: '注入预览',
    injectedKLineBarsCount: '个 ContextItem 已注入',
    composerPlaceholder: '询问当前图表',
    send: '发送',
    stop: '停止',
    action: '操作',
    reasoning: '思考',
    reasoningEffort: '推理强度',
    collapseReasoning: '折叠思考过程',
    input: '输入',
    output: '输出',
    total: '共计',
    result: '结果',
    evidence: '证据',
    locate: '在图表中定位',
    undo: '撤销',
    retry: '重试',
    copyMessage: '复制',
    copiedMessage: '已复制',
    copyFailed: '复制失败',
    regenerate: '重新生成',
    editMessage: '编辑消息',
    saveAndSend: '保存并发送',
    editFailed: '修改后的消息发送失败。',
    editBusy: '请等待当前回复结束后再编辑。',
    editUnavailable: '此消息已不在当前对话中。',
    confirm: '确认',
    cancel: '取消',
    reject: '拒绝',
    reversible: '可撤销',
    irreversible: '不可撤销',
    required: '需要确认',
    recommended: '建议操作',
    question: {
      required: '需要澄清',
      submit: '提交回答',
      freeText: '或直接输入你的要求',
      answered: '已回答',
      cancelled: '提问已取消',
    },
    tokens: 'tokens',
    providerSettings: '供应商设置',
    tools: '工具',
    noTools: '当前没有已注册的 Agent 工具。',
    toolParameters: '参数（JSON）',
    toolRun: '运行',
    toolRunning: '运行中...',
    providerProfile: '配置',
    managedProviderNotice: '此配置已为你托管，无需填写 API Key 或选择模型。',
    providerProfileName: '配置名称',
    providerProfileNameDuplicated: '已存在同名配置。',
    newProviderProfile: '新建配置',
    renameProviderProfile: '重命名配置',
    deleteProviderProfile: '删除配置',
    deleteProviderProfileConfirm: '删除这个配置？其模型池也会一并移除。',
    apiProtocol: 'API 协议',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: '留空则保留已保存的 Key',
    save: '保存',
    additionalHeaders: '附加请求头（JSON）',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "我的应用"\n}',
    model: '选择模型',
    modelList: '可用模型',
    modelPool: '模型池',
    contextWindow: '上下文',
    noModelsInPool: '请至少向模型池添加一个模型。',
    loadingModels: '正在加载模型...',
    refreshModels: '刷新模型列表',
    modelSearchPlaceholder: '搜索',
    apiKeyPlaceholder: '留空则使用已保存的凭据',
    modelPlaceholder: '选择模型',
    sessionNamePrompt: '会话名称',
    deleteSessionConfirm: '删除这个会话？',
    status: {
      idle: '就绪',
      running: '运行中',
      cancelling: '正在停止',
      completed: '已完成',
      failed: '失败',
      cancelled: '已取消',
      partial: '部分完成',
      interrupted: '已中断',
      queued: '排队中',
      'requires-confirmation': '等待确认',
      succeeded: '成功',
      confirmed: '已确认',
      rejected: '已拒绝',
      expired: '已过期',
      undone: '已撤销',
    },
  },
} as const

/** 指定语言的完整界面文案。 */
export type AgentCopy = (typeof copy)[AgentLocale]

/** 返回指定语言的界面文案。 */
export function getAgentCopy(locale: AgentLocale): AgentCopy {
  return copy[locale]
}
