#!/usr/bin/env tsx
// 对比度报告：WCAG AA（门槛）+ APCA（建议），覆盖 mode × preset × 涨跌约定。
//
//   pnpm tokens:contrast                  重写 design-tokens/reports/contrast.{md,json}
//   pnpm tokens:contrast --update-known   同时把当前全部 AA 失败记为已知（仅在评审接受后使用）
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  APCA_ADVISORY,
  type AuditRow,
  auditAll,
  findRegressions,
  type KnownFailures,
  WCAG_FLOOR,
} from '../../src/foundation/tokens/__tests__/contrastAudit.ts'

const coreDir = fileURLToPath(new URL('../../', import.meta.url))
const knownFile = path.join(coreDir, 'src/foundation/tokens/__tests__/contrast-known-failures.json')
const outDir = path.join(coreDir, 'design-tokens/reports')

const rows = auditAll()
const failures = rows.filter((r) => !r.pass)

if (process.argv.includes('--update-known')) {
  const known: KnownFailures = {
    $comment:
      'Accepted WCAG AA failures of the current palettes (Phase 1 baseline). contrastGate.test.ts fails only on pairs not listed here, or listed pairs whose ratio drops further. Phase 3 (preset regeneration) should empty this list. Regenerate with `pnpm tokens:contrast --update-known` only after review.',
    failures: Object.fromEntries(failures.map((r) => [r.key, r.wcag])),
  }
  fs.writeFileSync(knownFile, `${JSON.stringify(known, null, 2)}\n`)
}
const known: KnownFailures = JSON.parse(fs.readFileSync(knownFile, 'utf8'))
const regressions = findRegressions(rows, known)
const failingKeys = new Set(failures.map((r) => r.key))
const resolved = Object.keys(known.failures).filter((k) => !failingKeys.has(k))

/** Group rows that differ only by up/down convention. */
function group(list: readonly AuditRow[]) {
  const map = new Map<string, { row: AuditRow; conventions: string[] }>()
  for (const r of list) {
    const k = `${r.preset}/${r.mode}/${r.pair.id}/${r.wcag}`
    const g = map.get(k)
    if (g) g.conventions.push(r.convention)
    else map.set(k, { row: r, conventions: [r.convention] })
  }
  return [...map.values()]
}

const combos = new Set(rows.map((r) => `${r.preset}/${r.mode}/${r.convention}`)).size
const apcaFlags = rows.filter((r) => !r.apcaAdvisoryPass)
const md = [
  '<!-- Generated by `pnpm tokens:contrast`. Do not edit. -->',
  '# Contrast report',
  '',
  `Scope: ${combos} combinations (5 presets × light/dark × green-up/red-up), ${rows.length / combos} declared pairs each, ${rows.length} checks. Pairs: \`src/foundation/tokens/__tests__/contrastAudit.ts\`.`,
  '',
  `- **WCAG 2 AA (CI gate)**: text ≥ ${WCAG_FLOOR.text}:1, UI ≥ ${WCAG_FLOOR.ui}:1. ${failures.length} failing checks, all recorded as known (Phase 1 baseline); ${regressions.length} regressions; ${resolved.length} known failures now pass.`,
  `- **APCA (advisory)**: text |Lc| ≥ ${APCA_ADVISORY.text}, UI |Lc| ≥ ${APCA_ADVISORY.ui} (≈ 4.5:1 / 3:1, craft-principles CP 5, S25). ${apcaFlags.length} checks below the advisory level. Not a gate: APCA is beta with a non-OSI license (tooling.md).`,
  '',
  '## WCAG AA failures (known, for Phase 3)',
  '',
  '| preset | mode | pair | kind | fg | bg | WCAG | floor | APCA Lc | conventions |',
  '|---|---|---|---|---|---|---|---|---|---|',
  ...group(failures).map(
    ({ row: r, conventions }) =>
      `| ${r.preset} | ${r.mode} | ${r.pair.id} | ${r.pair.kind} | \`${r.fg}\` | \`${r.bg}\` | ${r.wcag} | ${r.floor}:1 | ${r.apca} | ${conventions.join(', ')} |`,
  ),
  '',
  '## APCA advisory flags (pass WCAG AA, below the APCA level)',
  '',
  '| preset | mode | pair | kind | WCAG | APCA Lc | advisory |',
  '|---|---|---|---|---|---|---|',
  ...group(apcaFlags.filter((r) => r.pass)).map(
    ({ row: r }) =>
      `| ${r.preset} | ${r.mode} | ${r.pair.id} | ${r.pair.kind} | ${r.wcag} | ${r.apca} | ${APCA_ADVISORY[r.pair.kind]} |`,
  ),
  '',
].join('\n')

const json = rows.map((r) => ({
  preset: r.preset,
  mode: r.mode,
  convention: r.convention,
  pair: r.pair.id,
  kind: r.pair.kind,
  fg: r.fg,
  bg: r.bg,
  wcag: r.wcag,
  apca: r.apca,
  pass: r.pass,
}))

fs.mkdirSync(outDir, { recursive: true })
fs.writeFileSync(path.join(outDir, 'contrast.md'), md)
fs.writeFileSync(path.join(outDir, 'contrast.json'), `${JSON.stringify(json, null, 2)}\n`)
process.stdout.write(
  `tokens:contrast — ${rows.length} checks, ${failures.length} AA failures (${regressions.length} regressions), ${apcaFlags.length} APCA advisories.\n`,
)
if (regressions.length) process.exitCode = 1
